CREATE SCHEMA ImplantaDEVTraining;

DROP TABLE ImplantaDEVTraining.Enderecos;
DROP TABLE ImplantaDEVTraining.Profissionais;
DROP TABLE ImplantaDEVTraining.Categorias;

CREATE TABLE ImplantaDEVTraining.Categorias
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Nome VARCHAR(250) NOT NULL,
	Ativo BIT NOT NULL DEFAULT 1
)

CREATE TABLE ImplantaDEVTraining.Profissionais
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Nome VARCHAR(250) NOT NULL,
	DataNascimento DATETIME2(2) NULL,
	Ativo BIT NOT NULL DEFAULT 1,
	CPF VARCHAR(15) NULL,
	RG VARCHAR(20) NULL,
	Observacoes VARCHAR(MAX) NULL,
	IdCategoria UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES ImplantaDEVTraining.Categorias
);

CREATE TABLE ImplantaDEVTraining.Enderecos
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	IdProfissional UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES ImplantaDEVTraining.Profissionais ON DELETE CASCADE,
	CEP VARCHAR(15) NOT NULL,
	Logradouro VARCHAR(300) NOT NULL,
	Bairro VARCHAR(250) NOT NULL,
	Cidade VARCHAR(250) NOT NULL,
	Numero VARCHAR(20) NULL
);






